language: node_js
node_js:
- '8'
before_install:
- npm i -g npm@5.8
deploy:
  provider: npm
  email: aurimas.vlcnks@gmail.com
  api_key:
    secure: GYbfVoYx5OJDun9FtVPRhDUsNJdLdH3cslivVdc2eAgxQInnynTZIrxAstbpMUeXnyL2P+H1czr/wguRJqsTgy1D3WtLJFn7sxMnZzhmoqQ0sxQwBNQwHxvD6azjvyLzIDQoiv3BRYjiuJ11LXVpL53BGCY6UJVDodPEstm83/PGiXYJFq15iWR70QsJPdTwTTKF/RS7KfvheHeISGRElzEETN53AGDki2IXTjhvGDCIstHl6Jvlj0iRgQM5zc3/9boKfoV1Ku4rUa9ztHyOLUPiqn4FfCbvvkWQovb0gDytRd7AtHhSJZaF/iI7nmRL+iZxiGL+74rgFiRD9HkaylQqHKAud4SUp3V9GYRWy6EXxIrISYq6coILtPabZDis83vZ/L4zMsiZJhBTh73Q3uIPf3juOBE0loapHzBrbk7z8CGR9vpu7iis3OMZk3reALdM69Pynb2aGD3TCePrWwcnP7w1qQ6xO6t4X8lxiE6Iqm7xQAiAQ64eF7xKTGO4k3bRuE3uL0C/EnQJkyNQLJs1obtkQ4G9Qmz+rulKKAhdPKCeaeOa7ziigYaoBckl6XmbWy+eTyvytFkm52OuZ+N7CALLhQBPdEF1d+WKOwRpjaqqB7Ub3533eS0HiKfHySH0C5LY5R25xGYZzCPtlN5BzGllYnS67vV+sLqLxhg=
  on:
    tags: true
    repo: aurimas4/tools-demo
  skip_cleanup: true
before_deploy:
  - cat ~/.npmrc
after_deploy:
  - cat ~/.npmrc