language: node_js
matrix:
  include:
    - node_js: 8
    - node_js: 9
    - node_js: 10
      env: PUBLISH="true"
deploy:
  provider: npm
  email: aurimas.vlcnks@gmail.com
  api_key:
    secure: YWlUezMsU1RXcgOODo7Fw8hDlozJFGd1q6ik2XxjzSJXe1AthnAhHSZBfYuTCHH8IKw4k2CVpMApMzcS1y3AgSLxAp9Iq8fK2uCZu9XTLVVF0YYuXvSyJGxcmw/B2eT+Ou1admZG4SuJKw2WqJlduoVGFWGU4Y2WtnvGMt3Hm1Rk0VAC5lenLv7hJ5QMZOIJ57kNwU/2hjjvcQlEeQYiNy4ZYUuxaH2UlIqjeTB9WBNI+2Yp1dLBVPqyF1d8km87gcZh2yCOxCdJaKQqr2MDXVYceL/QUqoZohwHGRCzHYrsq13AIc7P918mT/9Jh+d5xikBG9yrjUv1gBbFkK7AoukPbo+hus+dRrXgiuu2RGQgPastCnH9/Ad1/fpcjjPOrzZV+Pj5omPAooQUy2n2Fbc3ZzDZoK0BAB7BM9tqg0+4J/VA/o2HOtxumjOQeR6SG0gm0C6H1RS68yHs3+77dqa9cd9daU4BivD9EEazi/HhBmoPcw0pPy0M9bTczHgDvjBdzKX3p1bTAX3HOydOT9X+iRnoi7dJ2tfwjHd1yM/zxkrNop4OpbnYN7WKg/dQxM+BKjDejT7oLcr54TqCVCIdpv2Sd3MzgL/MxSE3E+MqR5ArcQjo2Rlon6j0jkKypBsOGZtpQHMSsuJ13bew07/h0bdZZsVjT6f+MvbVoAE=
  on:
    tags: true
    repo: aurimas4/tools-demo
    condition: "$PUBLISH = true"
  skip_cleanup: true