language: node_js
node_js:
- '9'
before_install:
- npm i -g npm@6.9
deploy:
  provider: npm
  email: aurimas.vlcnks@gmail.com
  api_key:
    secure: JeXPKg1iN+PW81Ox/J1hDq+DCZ4wUIQm6p8GCNWCdihA1SNfwAMynI8A1tWTyP6KfSoF55NgeXfCWS5QgYHiiKCnaaLwGaw/IirFafg75HtCcfKWvMldohrrf81lrX7ObbpnyZq6I4JQ56s0ytozL4czYlJ9ZiQ0fSOeVejEOL1zNbWeK3/fnDLPmcGzHgr2g4ZQ2OSmjlPBFHZM9umP0hXKwYRr3ekccA7mdVEkmB063o8OunfCOTngfeU0pjEUMqMV9IgEVzfqq9TqMFl1T0ri0v/XZACDzaqMrjNDR3RPQgKFR+nCqU8oxqOcFNyUt8qRxgaOIP6npLgS9jm7HgY6Ld5QYme902GORdgBTKwvmttGKVJWMQn5SAnxc0vGZAX+NbgsxxUhALEGV5a+r6XOsNhdPzshqtxZxvF8cIzmbm7ANUc17+Bsf1Ag8jwwBc2tw1UDYulMU2r22xCTAsXDIkPUfxT0hQfD/z9Xb+B11Pn7QtgJnuThudMWkPfPm0kiaLkZIqVwnCU4CE1x5HWZwhyARcjnUyWWbsddWJ9uVp0Ue5Sk6lZg4ntITdFOG4q8fcKuLthdJ+dhVFpkcnjZ8Cl7VBaOqQf0E9EKV+JUAT/LhTSJdsTjxEBFHkZ9P2FDjkP6QQUsFeR09XtyIIv1LknxDjC95SuZMEvrWaQ=
  on:
    tags: true
    repo: aurimas4/tools-demo
  skip_cleanup: true